---
# Variable precedence: all < parent group < child group < host
# Verify your Anible inventory with
#   ansible-inventory -i inventory/inventory.yaml --graph
#   ansible-inventory -i inventory/inventory.yaml --list
# 🛑 Inventory files are static - variables and filters are not evaluated!

ansible_become: no # ISE does not have a superuser/enable mode
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_ssh_user: "{{ lookup('env','ISE_REST_USERNAME') }}"
ansible_ssh_private_key_file: "{{ ssh_key_private_file }}"