---
# Variable precedence: all < parent group < child group < host
# Verify your Anible inventory with
#   ansible-inventory -i inventory/inventory.yaml --graph
#   ansible-inventory -i inventory/inventory.yaml --list
# 🛑 Inventory files are static - variables and filters are not evaluated!

ansible_become: true
ansible_connection: ssh
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_rsa
