---
- name: Delete a VPC on AWS
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yaml

  tasks:

    - name: Terminate every running instance
      amazon.aws.ec2_instance:
        state: absent
        filters:
          instance-state-name: running

    - name: List all managed nat gateways in "{{ aws_region }}"
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ aws_region }}"
      register: ngw

    # - name: Show VPC info
    #   ansible.builtin.debug:
    #     var: ngw
    #   ignore_errors: true

    - name: Delete nat gateway and wait for deleted status
      amazon.aws.ec2_vpc_nat_gateway:
        state: absent
        nat_gateway_id: "{{ ngw.result[0].nat_gateway_id }}"
        # release_eip: true
        wait: true
        wait_timeout: 500
        region: "{{ aws_region }}"

    # - amazon.aws.ec2_vpc_net_info:
    #   register: result

    # - name: Delete an existing VPC
    #   amazon.aws.ec2_vpc_net:
    #     vpc_id: "{{ result.vpcs[0].vpc_id }}"
    #     state: absent