---
- name: Create Local Connection to AWS VPN
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yaml

  tasks:

    - community.aws.ec2_vpc_vgw_info:
        # region: ap-southeast-2
        # profile: production
      register: vgw

    - community.aws.ec2_customer_gateway_info:
        # region: ap-southeast-2
        # filters:
        #   "tag:Name": test-customer-gateway
      register: cgw

    - community.aws.ec2_vpc_vpn_info:
        filters:
          state: available
      register: vpn

    - name: Delete the VPN connection
      community.aws.ec2_vpc_vpn:
        state: absent
        vpn_connection_id: "{{ vpn.vpn_connections[0].vpn_connection_id }}"

    - name: Delete Customer Gateway
      community.aws.ec2_customer_gateway:
        ip_address: "{{ cgw.customer_gateways[0].ip_address }}"
        name: "{{ cgw.customer_gateways[0].tags.Name }}"
        bgp_asn: "{{ cgw.customer_gateways[0].bgp_asn }}"
        state: absent
        region: "{{ aws_region }}"
      register: cgw

    - name: Remove the VGW
      community.aws.ec2_vpc_vgw:
        state: absent
        region: "{{ aws_region }}"
        name: "{{ vgw.virtual_gateways[0].tags[4].value }}"
      register: deleted_vgw


